window.STARTUPCAMP_REQUIREMENTS = [
  {
    "id": "U10-001",
    "version": "V1.0",
    "side": "用户端",
    "module": "登录注册",
    "title": "多角色登录与身份选择",
    "priority": "P0",
    "status": "已上线",
    "source": "前端已核对：少年马斯克-login.html",
    "acceptance": "登录页已包含密码登录、验证码登录、记住密码和免费注册入口。",
    "type": "已确认"
  },
  {
    "id": "U10-002",
    "version": "V1.0",
    "side": "用户端",
    "module": "学员端",
    "title": "学员首页、任务、课程、团队、Idea、相册",
    "priority": "P0",
    "status": "已上线",
    "source": "前端已核对：少年马斯克.html",
    "acceptance": "学员端已包含我的课程、资料下载、营地任务、任务提交、创业想法、我的团队、云相册等入口。",
    "type": "已确认"
  },
  {
    "id": "U10-003",
    "version": "V1.0",
    "side": "用户端",
    "module": "家长端",
    "title": "家长首页、孩子切换、课程、相册、反馈",
    "priority": "P0",
    "status": "已上线",
    "source": "前端已核对：少年马斯克-jiazhang .html",
    "acceptance": "家长端已包含选择学员/营地、我的课程、老师点评、任务点评、问题反馈、云相册等入口。",
    "type": "已确认"
  },
  {
    "id": "U10-004",
    "version": "V1.0",
    "side": "用户端",
    "module": "老师端",
    "title": "老师首页、学生、记录、点评",
    "priority": "P0",
    "status": "已上线",
    "source": "前端已核对：少年马斯克-laoshi.html",
    "acceptance": "老师端已包含选择营地/班级、学生列表、管辖队伍设置、队伍成员管理、队员点评、学生详情等入口。",
    "type": "已确认"
  },
  {
    "id": "A10-001",
    "version": "V1.0",
    "side": "后台",
    "module": "营地管理",
    "title": "营地 CRUD、期数、时间、容量、状态",
    "priority": "P0",
    "status": "代码雏形",
    "source": "现有后台代码",
    "acceptance": "后台可维护营地基础信息、期数、时间、容量和状态。",
    "type": "已确认"
  },
  {
    "id": "A10-002",
    "version": "V1.0",
    "side": "后台",
    "module": "用户管理",
    "title": "学员、家长、老师、管理员账号管理",
    "priority": "P0",
    "status": "代码雏形",
    "source": "现有后台代码",
    "acceptance": "后台可维护多角色账号与基础权限。",
    "type": "已确认"
  },
  {
    "id": "A10-003",
    "version": "V1.0",
    "side": "后台",
    "module": "内容任务",
    "title": "课程、工作坊、资料、任务和提交",
    "priority": "P0",
    "status": "代码雏形",
    "source": "现有后台代码",
    "acceptance": "后台可维护内容、任务，并查看提交记录。",
    "type": "已确认"
  },
  {
    "id": "A10-004",
    "version": "V1.0",
    "side": "后台",
    "module": "记录点评",
    "title": "营地记录、任务点评、发布",
    "priority": "P0",
    "status": "代码雏形",
    "source": "现有后台代码",
    "acceptance": "后台可创建记录、点评任务并发布对外内容。",
    "type": "已确认"
  },
  {
    "id": "A10-005",
    "version": "V1.0",
    "side": "后台",
    "module": "相册反馈",
    "title": "相册发布、家长反馈处理",
    "priority": "P1",
    "status": "代码雏形",
    "source": "现有后台代码",
    "acceptance": "后台可发布相册，并处理家长反馈。",
    "type": "已确认"
  },
  {
    "id": "A10-006",
    "version": "V1.0",
    "side": "后台",
    "module": "导入导出",
    "title": "模板、导入、导出、任务记录",
    "priority": "P1",
    "status": "代码雏形",
    "source": "现有后台代码",
    "acceptance": "后台可执行模板下载、批量导入导出和任务追踪。",
    "type": "已确认"
  },
  {
    "id": "U11-001",
    "version": "V1.1",
    "side": "用户端",
    "module": "学员注册",
    "title": "学员 5 步注册：身份、档案、营地信息、问卷、账号确认",
    "priority": "P0",
    "status": "已设计待开发",
    "source": "对话 019f1d22",
    "acceptance": "20-24 页面形成完整建档链路。",
    "type": "已确认"
  },
  {
    "id": "U11-002",
    "version": "V1.1",
    "side": "用户端",
    "module": "家长注册",
    "title": "家长 5 步注册：问卷、安全、账号、绑定、确认报告",
    "priority": "P0",
    "status": "已设计待开发",
    "source": "对话 019f1d22",
    "acceptance": "25-29 页面形成家长绑定链路，确认页进入家长端。",
    "type": "已确认"
  },
  {
    "id": "U11-003",
    "version": "V1.1",
    "side": "用户端",
    "module": "老师注册",
    "title": "老师邀请注册、营地信息、审核确认",
    "priority": "P1",
    "status": "已设计待开发",
    "source": "对话 019f0cf6",
    "acceptance": "03-05 页面支持老师入营资料提交。",
    "type": "已确认"
  },
  {
    "id": "U11-004",
    "version": "V1.1",
    "side": "用户端",
    "module": "老师我的队伍",
    "title": "增加班级选择，去掉队伍点评/项目点评入口",
    "priority": "P0",
    "status": "已设计待开发",
    "source": "对话 019f0cf6",
    "acceptance": "06 页面只保留队伍查看和管理，不出现本期外点评入口。",
    "type": "已确认"
  },
  {
    "id": "U11-005",
    "version": "V1.1",
    "side": "用户端",
    "module": "学生管理",
    "title": "从学生点评改为学生管理，只保留查看信息和关注状态维护",
    "priority": "P0",
    "status": "已设计待开发",
    "source": "对话 019f0cf6",
    "acceptance": "07 页面不出现写寄语、查看记录。",
    "type": "已确认"
  },
  {
    "id": "U11-006",
    "version": "V1.1",
    "side": "用户端",
    "module": "老师每日任务",
    "title": "每天有个人/队伍/项目记录，特殊情况多选，Day5/6 项目材料",
    "priority": "P0",
    "status": "已设计待开发",
    "source": "对话 019f0cf6",
    "acceptance": "08 页面支持多类记录，字段结构化。",
    "type": "已确认"
  },
  {
    "id": "U11-007",
    "version": "V1.1",
    "side": "用户端",
    "module": "记录推送",
    "title": "每条记录确认后推送；未推送可改，推送后锁定；晚间总结给管理员",
    "priority": "P0",
    "status": "已设计待开发",
    "source": "对话 019f0cf6",
    "acceptance": "09 页面显示绑定来源、保存时间、推送范围和锁定状态。",
    "type": "已确认"
  },
  {
    "id": "U11-008",
    "version": "V1.1",
    "side": "用户端",
    "module": "学员每日记录",
    "title": "学员端 Day1-Day6 每天展示个人/队伍/项目记录",
    "priority": "P0",
    "status": "已设计待开发",
    "source": "对话 019f1d70",
    "acceptance": "22 页面记录卡片完整，详情按老师字段映射。",
    "type": "已确认"
  },
  {
    "id": "U11-009",
    "version": "V1.1",
    "side": "用户端",
    "module": "家长每日记录",
    "title": "家长端去掉工作成果展示，记录数据和学员端对齐",
    "priority": "P0",
    "status": "已设计待开发",
    "source": "对话 019f1d70",
    "acceptance": "23 页面仅保留孩子每日记录，支持横向滑动。",
    "type": "已确认"
  },
  {
    "id": "U11-010",
    "version": "V1.1",
    "side": "用户端",
    "module": "记录详情弹窗",
    "title": "学员/家长详情弹窗按老师端记录表字段展示",
    "priority": "P0",
    "status": "已设计待开发",
    "source": "对话 019f1d70",
    "acceptance": "个人/队伍/项目/材料类记录字段一一对应。",
    "type": "已确认"
  },
  {
    "id": "U11-011",
    "version": "V1.1",
    "side": "用户端",
    "module": "家长回执",
    "title": "家长可对单条记录输入回执并显示已回执卡片",
    "priority": "P1",
    "status": "已设计待开发",
    "source": "对话 019f1d70",
    "acceptance": "每条记录单独保存回执，不串记录。",
    "type": "已确认"
  },
  {
    "id": "U11-012",
    "version": "V1.1",
    "side": "用户端",
    "module": "家长手机端排序",
    "title": "窄屏按确认顺序展示，并支持每日记录横向滑动",
    "priority": "P1",
    "status": "已设计待开发",
    "source": "对话 019f1d70",
    "acceptance": "手机端顺序稳定，记录可滑动查看。",
    "type": "已确认"
  },
  {
    "id": "A11-101",
    "version": "V1.1",
    "side": "后台",
    "module": "营地上下文",
    "title": "全局营地选择影响用户、成员、队伍、课程、任务、记录等模块",
    "priority": "P0",
    "status": "待开发",
    "source": "现有后台规划",
    "acceptance": "切换营地后各模块默认过滤。",
    "type": "已确认"
  },
  {
    "id": "A11-102",
    "version": "V1.1",
    "side": "后台",
    "module": "营地日程",
    "title": "6 天 5 夜日程、每日活动、Workshop milestone、内容关联",
    "priority": "P0",
    "status": "待开发",
    "source": "用户端记录需求反推",
    "acceptance": "支撑 Day1-Day6 每日记录和项目 milestone。",
    "type": "已确认"
  },
  {
    "id": "A11-103",
    "version": "V1.1",
    "side": "后台",
    "module": "记录结构化",
    "title": "保存个人、队伍、项目、特殊情况、材料类记录字段",
    "priority": "P0",
    "status": "待开发",
    "source": "U11-006/U11-010",
    "acceptance": "用户端详情能按字段展示。",
    "type": "已确认"
  },
  {
    "id": "A11-104",
    "version": "V1.1",
    "side": "后台",
    "module": "记录推送状态机",
    "title": "草稿、已确认、已推送、撤回、锁定",
    "priority": "P0",
    "status": "待开发",
    "source": "U11-007",
    "acceptance": "推送后不可改，撤回需留痕。",
    "type": "已确认"
  },
  {
    "id": "A11-105",
    "version": "V1.1",
    "side": "后台",
    "module": "家长回执",
    "title": "保存家长记录回执、已读时间、回执内容",
    "priority": "P1",
    "status": "待开发",
    "source": "U11-011",
    "acceptance": "后台可查看每条记录回执。",
    "type": "已确认"
  },
  {
    "id": "A11-106",
    "version": "V1.1",
    "side": "后台",
    "module": "项目资料",
    "title": "Day5/Day6 项目材料提交、审核、推送家长",
    "priority": "P0",
    "status": "待开发",
    "source": "U11-006/U11-009",
    "acceptance": "PPT、宣传片等材料状态可追踪。",
    "type": "已确认"
  },
  {
    "id": "A11-107",
    "version": "V1.1",
    "side": "后台",
    "module": "学生关注状态",
    "title": "老师在学生信息里维护关注状态和备注",
    "priority": "P0",
    "status": "待开发",
    "source": "U11-005",
    "acceptance": "关注状态可在老师端和后台同步。",
    "type": "已确认"
  },
  {
    "id": "A11-108",
    "version": "V1.1",
    "side": "后台",
    "module": "招生表单",
    "title": "学员/家长/老师注册建档字段后台可配置或审核",
    "priority": "P0",
    "status": "待开发",
    "source": "U11-001/U11-002/U11-003",
    "acceptance": "注册数据进入后台审核和成员关系。",
    "type": "已确认"
  },
  {
    "id": "C12-001",
    "version": "V1.2候选",
    "side": "待讨论",
    "module": "通知中心 / 消息提醒",
    "title": "记录推送后是否需要短信、微信、站内通知？不同角色通知频率如何控制？",
    "priority": "待定",
    "status": "待讨论",
    "source": "U11-007 记录推送",
    "acceptance": "确认通知渠道、触发规则、频率和关闭策略。",
    "type": "候选"
  },
  {
    "id": "C12-002",
    "version": "V1.2候选",
    "side": "待讨论",
    "module": "成长报告自动汇总",
    "title": "是否要从每日记录自动生成周报/结营报告草稿？报告结构由谁审核？",
    "priority": "待定",
    "status": "待讨论",
    "source": "U11-010 详情字段映射",
    "acceptance": "确认报告结构、证据引用、审核角色和发布时间。",
    "type": "候选"
  },
  {
    "id": "C12-003",
    "version": "V1.2候选",
    "side": "待讨论",
    "module": "家校沟通闭环",
    "title": "家长回执是否需要老师回复？是否进入反馈工单？是否统计已读率？",
    "priority": "待定",
    "status": "待讨论",
    "source": "U11-011 家长回执",
    "acceptance": "确认回执后的处理链路、责任人和数据统计口径。",
    "type": "候选"
  },
  {
    "id": "C12-004",
    "version": "V1.2候选",
    "side": "待讨论",
    "module": "老师记录效率工具",
    "title": "是否需要语音转文字、批量记录、模板、常用语？哪些老师场景最痛？",
    "priority": "待定",
    "status": "待讨论",
    "source": "U11-006 多类记录",
    "acceptance": "确认最高频记录场景和首批效率工具。",
    "type": "候选"
  },
  {
    "id": "C12-005",
    "version": "V1.2候选",
    "side": "待讨论",
    "module": "日程模板库",
    "title": "6 天 5 夜是否固定？是否需要不同营地复制、调整、版本化？",
    "priority": "待定",
    "status": "待讨论",
    "source": "A11-102 营地日程",
    "acceptance": "确认日程模板、复制、版本和变更通知规则。",
    "type": "候选"
  },
  {
    "id": "C12-006",
    "version": "V1.2候选",
    "side": "待讨论",
    "module": "路演材料管理",
    "title": "项目材料是否需要版本、审核、评委可见、家长可见范围？",
    "priority": "待定",
    "status": "待讨论",
    "source": "A11-106 项目资料",
    "acceptance": "确认材料类型、版本、审核流和可见范围。",
    "type": "候选"
  },
  {
    "id": "C13-001",
    "version": "V1.3候选",
    "side": "待讨论",
    "module": "顾问老师协同",
    "title": "顾问老师是否能看项目记录并留下建议？建议是否对家长可见？",
    "priority": "待定",
    "status": "待讨论",
    "source": "队伍/项目记录",
    "acceptance": "确认顾问角色、授权范围、建议可见性和采纳流程。",
    "type": "候选"
  },
  {
    "id": "C13-002",
    "version": "V1.3候选",
    "side": "待讨论",
    "module": "投资人评委评审",
    "title": "是否需要评审场次、评分表、项目分配、结果锁定和发布？",
    "priority": "待定",
    "status": "待讨论",
    "source": "项目资料与路演",
    "acceptance": "确认评委工作台、评分维度、结果发布和锁定规则。",
    "type": "候选"
  },
  {
    "id": "C13-003",
    "version": "V1.3候选",
    "side": "待讨论",
    "module": "成长激励 / 徽章",
    "title": "是否需要积分、徽章、阶段成就？是否会引发排名和隐私问题？",
    "priority": "待定",
    "status": "待讨论",
    "source": "六维能力评估",
    "acceptance": "确认激励目标、隐私边界和是否展示排行。",
    "type": "候选"
  },
  {
    "id": "C14-001",
    "version": "V1.4候选",
    "side": "待讨论",
    "module": "AI 成长报告",
    "title": "AI 是否只生成草稿？引用哪些证据？老师审核流程怎么设计？",
    "priority": "待定",
    "status": "待讨论",
    "source": "AI 润色/记录",
    "acceptance": "确认 AI 证据引用、审核、发布和撤回规则。",
    "type": "候选"
  },
  {
    "id": "C14-002",
    "version": "V1.4候选",
    "side": "待讨论",
    "module": "AI 治理",
    "title": "模型、密钥、提示词、调用日志、降级开关由谁管理？",
    "priority": "待定",
    "status": "待讨论",
    "source": "AI 与提示词",
    "acceptance": "确认 AI 管理权限、审计字段、降级策略和成本控制。",
    "type": "候选"
  }
];
